### ISSUE TITLE
mailgun replied with empty body

### ISSUE THREAD

**Issue by tijs** [diasdavid/mailgun-validate-email#12]
I'm running into an issue where the validation fails because of an apparent 'empty body' returned by mailgun. This would seem like a body parser issue but i imagine this usually works fine so not sure if it's my code or mailgun who changed things?

Full trace:

```
Error: mailgun replied with empty body
    at Request._callback (/Users/tijs/Projects/bunka-landing/node_modules/mailgun-validate-email/src/index.js:22:19)
    at Request.self.callback (/Users/tijs/Projects/bunka-landing/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/tijs/Projects/bunka-landing/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/tijs/Projects/bunka-landing/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by daviddias** [comment]
I believe that is just mailgun, see: https://github.com/diasdavid/mailgun-validate-email/issues/6

**Comment by tijs** [comment]
K, thanks. Does indeed look like it. My key was incorrect which resulted in this. Will catch the errors on my end, thanks.
